### ISSUE TITLE
Could not pass event BlockRedstoneEvent to JukeLoop v0.1.4

### ISSUE THREAD

**Issue by liquidox** [andrepl/JukeLoop#8]
Two diff traces:

http://pastie.org/pastes/7609065/text?key=gqgw78gzc1ihawywqap9tw

And:

http://pastie.org/pastes/7609086/text?key=figfhf3cmgdwcsha8891q

**Comment by andrepl** [comment]
Those stacktraces appear to be incomplete.  there should be a section following that which says "Caused by XXXXXXXException at...." followed by another long section of code. that's the relevant part I need.  all this says is that there was an error, but not where or how it happened.  In this case since its a redstone error it would be helpful to know what the setup looks like which caused the error, I can see there's a pressure plate, what kind is it and where is it in relation to the jukebox?

**Comment by liquidox** [comment]
Doh, well can't find it now, as these error tracers don't appear in the server.log, only in console, so have to catch it live...

**Comment by andrepl** [comment]
If I had to guess, It seems it might be a redstone setup which I hadn't predicted, maybe a strangely positioned pressure plate, but I can't really tell without more detail. I'll try reproducing it with various perssureplate setups tonight and see what i can find.

**Comment by liquidox** [comment]
Full error from console now:

http://pastie.org/pastes/7634352/text?key=l0bgusrvdh8c6oieuu1qw

**Comment by andrepl** [comment]
Ok, the issue is caused by weighted pressure plates (iron/gold) because Bukkit hasn't implemented MaterialData classes for them yet.  All I could do for now is to remove support for them triggering jukeboxes.  there's a development build [here](http://mcgitlab.norcode.com:8081/job/JukeLoop/lastSuccessfulBuild/JukeLoop$JukeLoop/)
